// src/pages/index/index.tsx
import { Component, PropsWithChildren, useState } from "react";
import { View, Text, Button } from "@tarojs/components";
import "./index.scss";

export default function Index() {
  const [count, setCount] = useState(0);
  return (
    <View className="index">
      <Text>Hello world!!</Text>
      <Button onClick={() => setCount(count + 1)}>Click me ({count})</Button>
    </View>
  );
}

// src/pages/index/index.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useCounterStore } from '@/store'
// import { View } from '@tarojs/components'

const counter = useCounterStore()
const count = computed(() => counter.count)

function handleIncrementClicked() {
  counter.count++
}
</script>

<template>
  <view class="index">
    {{ count }}
    <nut-button @click="handleIncrementClicked">
      +1
    </nut-button>
  </view>
</template>
